# Generated by Django 4.2.6 on 2023-10-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preguntas',
            new_name='Pregunta',
        ),
        migrations.RenameModel(
            old_name='Respuestas',
            new_name='Respuesta',
        ),
    ]
